Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@morvin300 
gleidsonmt
/
Gleidsonmt
Public
Fork your own copy of gleidsonmt/Gleidsonmt
Code
Issues
Pull requests
Actions
Projects
Security
Insights
Gleidsonmt/.github/workflows/snake.yml
@gleidsonmt
gleidsonmt Update snake.yml
Latest commit 9074500 on Dec 29, 2021
 History
 1 contributor
26 lines (23 sloc)  647 Bytes

# This is a basic workflow to help you get started with Actions
name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: morvin300
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
